export const PERMISSIONS = [
  {
    id: 0,
    view: 'Tickets',
    function: 'Create new Tickets',
    description: undefined,
    admin: true,
    editor: true,
    requester: true,
  },
  {
    id: 1,
    view: 'Tickets',
    function: 'Modifying own tickets.',
    description: 'Change related course.',
    admin: true,
    editor: true,
    requester: true,
  },
  {
    id: 2,
    view: 'Tickets',
    function: 'Modifying own tickets.',
    description: 'Change title.',
    admin: true,
    editor: true,
    requester: true,
  },
  {
    id: 3,
    view: 'Tickets',
    function: 'Modifying own tickets.',
    description: 'Change description.',
    admin: true,
    editor: true,
    requester: true,
  },
  {
    id: 4,
    view: 'Tickets',
    function: 'Modifying own tickets.',
    description: 'Closing the ticket.',
    admin: true,
    editor: true,
    requester: true,
  },
  {
    id: 5,
    view: 'Tickets',
    function: 'Modifying tickets.',
    description: 'Change related course.',
    admin: true,
    editor: true,
    requester: false,
  },
  {
    id: 6,
    view: 'Tickets',
    function: 'Modifying tickets.',
    description: 'Change title.',
    admin: true,
    editor: true,
    requester: false,
  },
  {
    id: 7,
    view: 'Tickets',
    function: 'Modifying tickets.',
    description: 'Change description.',
    admin: true,
    editor: true,
    requester: false,
  },
  {
    id: 8,
    view: 'Tickets',
    function: 'Modifying tickets.',
    description: 'Closing the ticket.',
    admin: true,
    editor: true,
    requester: false,
  },
  {
    id: 9,
    view: 'Tickets',
    function: 'Modifying tickets.',
    description: 'Change Assigne.',
    admin: true,
    editor: true,
    requester: false,
  },
  {
    id: 10,
    view: 'Tickets',
    function: 'Modifying tickets.',
    description: 'Change Priority.',
    admin: true,
    editor: true,
    requester: false,
  },
  {
    id: 11,
    view: 'Tickets',
    function: 'Modifying tickets.',
    description: 'Change Status.',
    admin: true,
    editor: true,
    requester: false,
  },
  {
    id: 12,
    view: 'Tickets',
    function: 'Show tickets.',
    description: 'List own tickets.',
    admin: true,
    editor: true,
    requester: true,
  },
  {
    id: 13,
    view: 'Tickets',
    function: 'Show tickets.',
    description: 'List all tickets.',
    admin: true,
    editor: true,
    requester: false,
  },
  {
    id: 14,
    view: 'Tickets',
    function: 'Comments.',
    description: 'Add comment to own ticket.',
    admin: true,
    editor: true,
    requester: true,
  },
  {
    id: 15,
    view: 'Tickets',
    function: 'Comments.',
    description: 'Add comment to ticket.',
    admin: true,
    editor: true,
    requester: false,
  },
  {
    id: 16,
    view: 'Settings',
    function: 'Permissions.',
    description: 'Change permissions.',
    admin: true,
    editor: false,
    requester: false,
  },
  {
    id: 17,
    view: 'Settings',
    function: 'Course Management.',
    description: 'Delete course.',
    admin: true,
    editor: false,
    requester: false,
  },
  {
    id: 18,
    view: 'Settings',
    function: 'Course Management.',
    description: 'Create course.',
    admin: true,
    editor: false,
    requester: false,
  },
  {
    id: 19,
    view: 'Settings',
    function: 'Course Management.',
    description: 'Change course name.',
    admin: true,
    editor: false,
    requester: false,
  },
  {
    id: 20,
    view: 'Settings',
    function: 'Course Management.',
    description: 'Change courseabbreviation.',
    admin: true,
    editor: false,
    requester: false,
  },
  {
    id: 21,
    view: 'Settings',
    function: 'User Management.',
    description: 'Change user name.',
    admin: true,
    editor: false,
    requester: false,
  },
  {
    id: 22,
    view: 'Settings',
    function: 'User Management.',
    description: 'Change user e-mail.',
    admin: true,
    editor: false,
    requester: false,
  },
  {
    id: 23,
    view: 'Settings',
    function: 'User Management.',
    description: 'Change user role.',
    admin: true,
    editor: false,
    requester: false,
  },
  {
    id: 24,
    view: 'Profil',
    function: 'Modify own profile.',
    description: 'Change password.',
    admin: true,
    editor: true,
    requester: true,
  },
  {
    id: 25,
    view: 'Profil',
    function: 'Modify own profile.',
    description: 'Change e-mail.',
    admin: true,
    editor: true,
    requester: true,
  },
  {
    id: 26,
    view: 'Profil',
    function: 'Modify own profile.',
    description: 'Change name.',
    admin: true,
    editor: true,
    requester: true,
  },
];
