name: Deploy Frontend to Firebase Hosting on merge
on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: frontend

jobs:
  ci:
    name: Continuous Integration Frontend
    uses: ./.github/workflows/ci-frontend_without_audit.yml
    secrets: inherit

  deploy:
    name: Deploy Frontend to Firebase
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.1.0
      - name: Download artifacts
        uses: actions/download-artifact@v3.0.2
        with:
          name: dist
          path: './frontend/dist/'
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROJEKT_SOFTWARE_ENGINEERING }}'
          channelId: live
          projectId: projekt-software-engineering
          entryPoint: './frontend'
